name: Balance Data Correction
description: Report missing or incorrect balance changes
title: "[Data] "
labels: ["data"]
body:
  - type: markdown
    attributes:
      value: |
        **Help us fix the data!**
        
        BAD: "Toss nerfs missing, fix it!"
        BAD: "Source: everyone knows that!"
        
        Please provide a concrete example and a source link.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What is incorrect?
      placeholder: "e.g., Zergling speed cost is 100/100, should be 200/200."
    validations:
      required: true

  - type: input
    id: source
    attributes:
      label: Source
      description: Link to Blizzard or Liquipedia.
      placeholder: https://liquipedia.net/starcraft2/Patch_X.Y.Z
    validations:
      required: true

  - type: input
    id: link
    attributes:
      label: Visualization Link
      placeholder: https://p.migdal.pl/sc2-balance-timeline/...

